name: Build app and deploy to NPM & Sync Code To Gitee
on:
  #ç›‘å¬pushæ“ä½œ
  push:
    branches:
      # masteråˆ†æ”¯ï¼Œä½ ä¹Ÿå¯ä»¥æ”¹æˆå…¶ä»–åˆ†æ”¯
      - master
jobs:
  job_1:
    name: job 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test job 1 on the runner."
  job_2:
    name: job 2
    runs-on: ubuntu-latest
    steps:
     - run: echo "ğŸ–¥ï¸ The workflow is now ready to test job 1  on the runner."
  job_3:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - name: Check out repository code
          uses: actions/checkout@v2
        - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
        - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
        - name: List files in the repository
          run: |
            ls ${{ github.workspace }}
        - run: echo "ğŸ This job's status is ${{ job.status }}."   
#   Sync-Code-To-Gitee-job:
#     # runs-on æŒ‡å®šjobä»»åŠ¡è¿è¡Œæ‰€éœ€è¦çš„è™šæ‹Ÿæœºç¯å¢ƒ
#     runs-on: ubuntu-latest
#     steps:
#       # åŒæ­¥ä»£ç åˆ° gitee
#     - name: Sync Github Repos To Gitee  # åå­—éšä¾¿èµ·
#       uses: Yikun/hub-mirror-action@v1.1  # ä½¿ç”¨Yikun/hub-mirror-action
#       with:
#         src: github/Daudxu
#         dst: gitee/coding-365
#         dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSHå¯†é’¥å¯¹ä¸­çš„ç§é’¥
#         dst_token:  ${{ secrets.GITEE_TOKEN }}  # Giteeè´¦æˆ·çš„ç§äººä»¤ç‰Œ
#         account_type: user  # è´¦æˆ·ç±»å‹
#         clone_style: "https"  # ä½¿ç”¨httpsæ–¹å¼è¿›è¡Œcloneï¼Œä¹Ÿå¯ä»¥ä½¿ç”¨ssh
#         debug: true  # å¯ç”¨åä¼šæ˜¾ç¤ºæ‰€æœ‰æ‰§è¡Œå‘½ä»¤
#         force_update: true  # å¯ç”¨åï¼Œå¼ºåˆ¶åŒæ­¥ï¼Œå³å¼ºåˆ¶è¦†ç›–ç›®çš„ç«¯ä»“åº“
#         static_list: 'nft-lands-tile-map-vue-component'  # é™æ€åŒæ­¥åˆ—è¡¨ï¼Œåœ¨æ­¤å¡«å†™éœ€è¦åŒæ­¥çš„ä»“åº“åç§°ï¼Œå¯å¡«å†™å¤šä¸ª
#         timeout: '600s'  # gitè¶…æ—¶è®¾ç½®ï¼Œè¶…æ—¶åä¼šè‡ªåŠ¨é‡è¯•gitæ“ä½œ
